from enum import Enum


class LightsSwitchStrategy(Enum):
    OPPOSITE_DIRECTIONS_GREEN = "OPPOSITE_DIRECTIONS_GREEN"
    SINGLE_DIRECTION_GREEN = "SINGLE_DIRECTION_GREEN"
    MOST_CARS_GREEN_BASIC = "MOST_CARS_GREEN_BASIC"
    MOST_CARS_GREEN_WAITING = "MOST_CARS_GREEN_WAITING"
    MAX_WAIT_GREEN = "MAX_WAIT_GREEN"

    def __str__(self):
        return self.value
